version: "2"
services:
  php:
      build: ./docker/php/
      container_name: php_app
      working_dir: /var/www/html
      expose:
          - "9000"
      volumes:
          - ./api/:/var/www/html
      links:
          - mysql
  nginx:
      image: nginx:latest
      container_name: nginx_app
      working_dir: /usr/share/nginx/email-trans
      ports:
          - "8080:80"
      volumes:
          - ./:/usr/share/nginx/email-trans
          - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      links:
          - php
  mysql:
      image: mysql:5.7
      container_name: mysql_app
      ports:
          - "33060:3306"
      volumes:
         - ./docker/mysql/data:/var/lib/mysql
         - ./docker/mysql/sql:/var/local/sql
      environment:
        - MYSQL_DATABASE=transactional-email
        - MYSQL_ROOT_PASSWORD=dPtGssaSjK5h8aKP