name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tmails-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Docker
      run:  docker-compose up --build -d    
    - name: Copy .env
      run:  docker exec php_app bash || php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: docker exec php_app bash || composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Generate key
      run: docker exec php_app bash || php artisan key:generate
    - name: Directory Permissions
      run: docker exec php_app bash || chmod -R 777 storage bootstrap/cache
    - name: Generate db
      run: docker exec php_app bash || php artisan migrate
    - name: Login to GitHub Docker Registry
      run: docker login docker.pkg.github.com --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      env:
          DOCKER_USERNAME: ${{ secrets.GITHUB_DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_DOCKER_PASSWORD }}
    - name: push 
      run: docker push sonambhatnagar/temails:tagname
